### PR TITLE
Added registration page component

### PR DESCRIPTION
**Pull request by kaalage**

### CODE REVIEW

**Review by kim-n-lee — APPROVED** [review]
Runs correctly and looks good on my end!  Will need to add in links to connect back to landing page.

**Review by RoohieK — COMMENTED** [review]
Hi Karina, I have some comments to make on the registration component. I strongly believe that we need to link the data input in the registration form with the User class. I also , believe we need to have a user class for this.

**Review by ashleyglenn0 — APPROVED** [review]

**Comment by ashleyglenn0** [comment]
> Hi Karina, I have some comments to make on the registration component. I strongly believe that we need to link the data input in the registration form with the User class. I also , believe we need to have a user class for this.

I would echo this consideration.

**Comment by ashleyglenn0** [comment]
> > Hi Karina, I have some comments to make on the registration component. I strongly believe that we need to link the data input in the registration form with the User class. I also , believe we need to have a user class for this.
> 
> I would echo this consideration.

We can still merge these changes. Just create a new branch and add it if that's the route you decide to go

**Review by RoohieK — APPROVED** [review]
The page works for me.

**Pull request merged**
